[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 10000
evm_version = "cancun"
FORGE_SNAPSHOT_CHECK = true
gas_reports = ["RouterV2", "Router"]
